# Чтобы подключить файл bashrc, надо выполнить source bashrc
alias gd="git diff"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gl="git log --oneline"
alias clean="rm - f *.pyc *.swp"
alias cdw="cd session_2"

